companieshouse/dissolution-api

- src/main/java/uk/gov/companieshouse/mapper/DissolutionResponseMapper.java
- src/main/java/uk/gov/companieshouse/model/Constants.java
- src/main/java/uk/gov/companieshouse/model/db/DissolutionGetDirector.java
- src/test/java/uk/gov/companieshouse/mapper/DissolutionResponseMapperTest.java
Update kind
Do not render null director null fields
> Change createdBy to email instead of user id

- src/main/java/uk/gov/companieshouse/controller/DissolutionController.java
- src/main/java/uk/gov/companieshouse/controller/ExceptionHandlerController.java
- src/main/java/uk/gov/companieshouse/exception/DirectorNotPendingApprovalException.java
- src/main/java/uk/gov/companieshouse/mapper/DirectorApprovalMapper.java
- src/main/java/uk/gov/companieshouse/mapper/DissolutionResponseMapper.java
- src/main/java/uk/gov/companieshouse/model/db/DirectorApproval.java
- src/main/java/uk/gov/companieshouse/model/db/DissolutionDirector.java
- src/main/java/uk/gov/companieshouse/model/dto/DissolutionPatchRequest.java
- src/main/java/uk/gov/companieshouse/model/dto/DissolutionPatchResponse.java
- src/main/java/uk/gov/companieshouse/service/DissolutionGetter.java
- src/main/java/uk/gov/companieshouse/service/DissolutionPatcher.java
- src/main/java/uk/gov/companieshouse/service/DissolutionService.java
- src/test/java/uk/gov/companieshouse/controller/DissolutionControllerTest.java
- src/test/java/uk/gov/companieshouse/fixtures/DissolutionFixtures.java
- src/test/java/uk/gov/companieshouse/mapper/DirectorApprovalMapperTest.java
- src/test/java/uk/gov/companieshouse/mapper/DissolutionResponseMapperTest.java
- src/test/java/uk/gov/companieshouse/service/DissolutionGetterTest.java
- src/test/java/uk/gov/companieshouse/service/DissolutionPatcherTest.java
- src/test/java/uk/gov/companieshouse/service/DissolutionServiceTest.java
- for single director authorisation and approval
> S4-82: Added PATH endpoint 

- src/main/java/uk/gov/companieshouse/controller/DissolutionController.java
- src/test/java/uk/gov/companieshouse/controller/DissolutionControllerTest.java
> Add request body to patch endpoint and use it in logic

- pom.xml
- src/main/java/uk/gov/companieshouse/client/BarcodeGeneratorClient.java
- src/main/java/uk/gov/companieshouse/config/ApiConfig.java
- src/main/java/uk/gov/companieshouse/config/BarcodeGeneratorConfig.java
- src/main/java/uk/gov/companieshouse/mapper/DissolutionRequestMapper.java
- src/main/java/uk/gov/companieshouse/mapper/barcode/BarcodeMapper.java
- src/main/java/uk/gov/companieshouse/model/db/dissolution/DissolutionApplication.java
- src/main/java/uk/gov/companieshouse/model/dto/barcode/BarcodeRequest.java
- src/main/java/uk/gov/companieshouse/model/dto/barcode/BarcodeResponse.java
- src/main/java/uk/gov/companieshouse/service/barcode/BarcodeGenerator.java
- src/main/java/uk/gov/companieshouse/service/dissolution/DissolutionCreator.java
- src/main/resources/application.yml
- src/test/java/uk/gov/companieshouse/client/BarcodeGeneratorClientTest.java
- src/test/java/uk/gov/companieshouse/fixtures/BarcodeFixtures.java
- src/test/java/uk/gov/companieshouse/mapper/DissolutionRequestMapperTest.java
- src/test/java/uk/gov/companieshouse/mapper/barcode/BarcodeMapperTest.java
- src/test/java/uk/gov/companieshouse/service/DissolutionCreatorTest.java
- src/test/java/uk/gov/companieshouse/service/barcode/BarcodeGeneratorTest.java
- src/test/resources/application.yml
Docker CHS Development - https://github.com/companieshouse/docker-chs-development/pull/29
> feature/S4-152 - Generate Barcode

- src/main/resources/pdf_templates/llds01.html
Modified font-size and layout for ds01 for consistency
PO approved these layouts.
> Create llds01 template

- pom.xml
- src/main/java/uk/gov/companieshouse/config/SecurityConfig.java
- src/main/java/uk/gov/companieshouse/controller/DissolutionController.java
- src/main/java/uk/gov/companieshouse/exception/GlobalExceptionHandler.java
- src/main/java/uk/gov/companieshouse/exception/UnauthorisedException.java
- src/main/java/uk/gov/companieshouse/interceptor/DissolutionTokenPermissionsInterceptor.java
- src/test/java/uk/gov/companieshouse/controller/DissolutionControllerTest.java
- src/test/java/uk/gov/companieshouse/interceptor/DissolutionTokenPermissionsInterceptorTest.java
- src/test/resources/application.yml
Dissolution API - https://github.com/companieshouse/dissolution-api/pull/33
account.ch.gov.uk - https://github.com/companieshouse/account.ch.gov.uk/pull/355
Docker CHS Dev - https://github.com/companieshouse/docker-chs-development/pull/31
api-security-java - https://github.com/companieshouse/api-security-java/pull/14
taf-api-karate- https://github.com/companieshouse/taf-api-karate/pull/187
Using secure default pattern, where endpoints must be whitelisted to not be checked.
> feature/S4-73 - Token Permissions

- src/main/java/uk/gov/companieshouse/mapper/chips/ChipsFormDataMapper.java
- src/main/java/uk/gov/companieshouse/model/dto/chips/xml/ChipsOfficer.java
- src/test/java/uk/gov/companieshouse/mapper/chips/ChipsFormDataMapperTest.java
> Add new fields to ChipsOfficer

- src/main/java/uk/gov/companieshouse/mapper/chips/ChipsFormDataMapper.java
- src/main/java/uk/gov/companieshouse/model/dto/chips/xml/ChipsOfficer.java
- src/test/java/uk/gov/companieshouse/mapper/chips/ChipsFormDataMapperTest.java
Reverts companieshouse/dissolution-api#36
> Revert "Add new fields to ChipsOfficer"

- src/main/java/uk/gov/companieshouse/service/CompanyOfficerValidator.java
- src/test/java/uk/gov/companieshouse/service/CompanyOfficerValidatorTest.java
Missed changes from previous pr
> S4-195: Expanded tests and fixed issue with officer role check

- src/main/java/uk/gov/companieshouse/repository/DissolutionRepository.java
- src/test/java/uk/gov/companieshouse/repository/dissolution/DissolutionRepositoryTest.java
> Change gte in query to lte.

- .github/dependabot.yml
Adding dependabot.yml file to enable dependancy scanning for maven and docker.
> Create initial dependabot.yml

- docker-compose.yaml
- pom.xml
- src/main/java/uk/gov/companieshouse/DissolutionApplication.java
- src/main/java/uk/gov/companieshouse/config/LoggingConfig.java
- src/main/java/uk/gov/companieshouse/controller/DissolutionController.java
- src/main/java/uk/gov/companieshouse/controller/HealthcheckController.java
- src/main/java/uk/gov/companieshouse/controller/PaymentController.java
- src/main/java/uk/gov/companieshouse/controller/SubmitController.java
- src/main/java/uk/gov/companieshouse/exception/GlobalExceptionHandler.java
- src/main/java/uk/gov/companieshouse/interceptor/LoggingInterceptor.java
- src/main/java/uk/gov/companieshouse/service/dissolution/certificate/DissolutionCertificateGenerator.java
- src/main/java/uk/gov/companieshouse/service/dissolution/chips/ChipsSubmitter.java
- src/main/java/uk/gov/companieshouse/service/email/EmailSerialiser.java
- src/main/java/uk/gov/companieshouse/service/email/EmailService.java
- src/main/resources/application.yml
- src/test/resources/application.yml
Change log driver behind SLF4J to use CH standard structured-logging. Disable dependancies for logback and log4j to ensure new driver is active.
> Change log driver behind SLF4J to use CH standard structured-logging.

- src/test/java/uk/gov/companieshouse/service/dissolution/certificate/DissolutionCertificateGeneratorTest.java
- src/test/java/uk/gov/companieshouse/service/dissolution/chips/ChipsSubmitterTest.java
- src/test/java/uk/gov/companieshouse/service/email/EmailSerialiserTest.java
- src/test/java/uk/gov/companieshouse/service/email/EmailServiceTest.java
> hotfix/S4-181 - Logging mock fix

- src/main/java/uk/gov/companieshouse/mapper/email/DissolutionEmailMapper.java
- src/main/java/uk/gov/companieshouse/model/Constants.java
- src/main/java/uk/gov/companieshouse/model/dto/email/PendingPaymentEmailData.java
- src/main/java/uk/gov/companieshouse/service/dissolution/DissolutionEmailService.java
- src/main/java/uk/gov/companieshouse/service/dissolution/DissolutionPatcher.java
- src/test/java/uk/gov/companieshouse/fixtures/EmailFixtures.java
- src/test/java/uk/gov/companieshouse/mapper/email/DissolutionEmailMapperTest.java
- src/test/java/uk/gov/companieshouse/service/dissolution/DissolutionPatcherTest.java
- src/test/java/uk/gov/companieshouse/service/email/DissolutionEmailServiceTest.java
Added code to send email requesting payment when dissolution status is set to "pending payment"
> S4-188: Added pending payment email logic

- .github/pull_request_template.md
- src/main/java/uk/gov/companieshouse/controller/ResponseController.java
- src/test/java/uk/gov/companieshouse/controller/ResponseControllerTest.java
Update `/response` endpoint to return HTTP status code 200.
> hotfix/S4-100: Update /response endpoint to return HTTP status code 200.

- src/main/java/uk/gov/companieshouse/mapper/chips/ChipsFormDataMapper.java
- src/main/java/uk/gov/companieshouse/model/dto/chips/xml/ChipsOfficer.java
- src/test/java/uk/gov/companieshouse/mapper/chips/ChipsFormDataMapperTest.java
This reverts commit ba974dfa
Add signatory information to CHIPS
- [ x] API (Karate) tests passing
- [ x] Pulled latest master into feature branch
- [ x] Code reviewed
- [ n/a] New Docker environment variables have also been added to the revel1 environment and cidev environment
- [ n/a] If your pull request depends on any other, please link them in the description
>  Add signatory information to CHIPS

- src/main/java/uk/gov/companieshouse/model/dto/payment/PaymentGetResponse.java
- src/main/java/uk/gov/companieshouse/service/dissolution/chips/ChipsResponseService.java
- src/main/java/uk/gov/companieshouse/service/payment/PaymentService.java
- src/test/java/uk/gov/companieshouse/service/dissolution/PaymentServiceTest.java
- src/test/java/uk/gov/companieshouse/service/dissolution/chips/ChipsResponseServiceTest.java
needed for company number to show up in payment reconciler CSVs
> hotfix/S4-199 - Add company number to get payment details response

- pom.xml
Reverts companieshouse/dissolution-api#52
> Revert "Bump maven-resources-plugin from 3.1.0 to 3.2.0"

- src/main/java/uk/gov/companieshouse/mapper/email/EmailMapper.java
- src/main/java/uk/gov/companieshouse/model/Constants.java
- src/main/java/uk/gov/companieshouse/model/dto/email/MessageType.java
- src/main/java/uk/gov/companieshouse/service/dissolution/DissolutionEmailService.java
- src/main/java/uk/gov/companieshouse/service/dissolution/DissolutionMessageTypeCalculator.java
- src/test/java/uk/gov/companieshouse/fixtures/EmailFixtures.java
- src/test/java/uk/gov/companieshouse/mapper/email/EmailMapperTest.java
- src/test/java/uk/gov/companieshouse/service/dissolution/DissolutionEmailServiceTest.java
- src/test/java/uk/gov/companieshouse/service/dissolution/DissolutionMessageTypeCalculatorTest.java
chs-notification-api - https://github.com/companieshouse/chs-notification-api/pull/201
dissolution-web - https://github.com/companieshouse/dissolution-web/pull/93
dissolution-api - https://github.com/companieshouse/dissolution-api/pull/61
Updated API to differentiate between DS01 and LLDS01 email templates.
> feature/S4-220 - Add LLDS01 emails

- src/main/java/uk/gov/companieshouse/mapper/DissolutionRequestMapper.java
- src/test/java/uk/gov/companieshouse/mapper/DissolutionRequestMapperTest.java
> Set director emails to lowercase

- src/main/java/uk/gov/companieshouse/model/enums/OfficerRole.java
- src/main/java/uk/gov/companieshouse/service/CompanyOfficerService.java
- src/test/java/uk/gov/companieshouse/service/CompanyOfficerServiceTest.java
Changed officer role validation to use an expanded list of roles.
Added to list:
- Corporate Director
- Corporate Nominee Director
- Judical Factor
- LLP Designated Member
- Corporate LLP Member
- Corporate LLP Designated Member
> S4-234: Added support for expanded list fo officer roles

- src/main/java/uk/gov/companieshouse/model/enums/CompanyType.java
- src/main/java/uk/gov/companieshouse/service/dissolution/validator/CompanyClosableValidator.java
- src/test/java/uk/gov/companieshouse/service/dissolution/validator/CompanyClosableValidatorTest.java
Support additional company types.
Relates to https://github.com/companieshouse/dissolution-web/pull/153
https://companieshouse.atlassian.net/browse/S4-285
> feature/S4-285: Support additional company types.

- src/main/java/uk/gov/companieshouse/service/dissolution/certificate/DissolutionCertificateGenerator.java
- src/main/java/uk/gov/companieshouse/service/dissolution/certificate/DissolutionCertificateLocationGenerator.java
- src/test/java/uk/gov/companieshouse/service/dissolution/certificate/DissolutionCertificateGeneratorTest.java
- src/test/java/uk/gov/companieshouse/service/dissolution/certificate/DissolutionCertificateLocationGeneratorTest.java
Update dissolution certificate PDF file name.
https://companieshouse.atlassian.net/browse/S4-276
> feature/S4-276: Update dissolution certificate PDF file name.

- src/main/java/uk/gov/companieshouse/client/PaymentsClient.java
- src/main/java/uk/gov/companieshouse/config/ApiConfig.java
- src/main/java/uk/gov/companieshouse/config/FeatureToggleConfig.java
- src/main/java/uk/gov/companieshouse/config/PaymentsConfig.java
- src/main/java/uk/gov/companieshouse/mapper/RefundInformationMapper.java
- src/main/java/uk/gov/companieshouse/mapper/RefundRequestMapper.java
- src/main/java/uk/gov/companieshouse/model/db/payment/PaymentInformation.java
- src/main/java/uk/gov/companieshouse/model/db/payment/RefundInformation.java
- src/main/java/uk/gov/companieshouse/model/dto/payment/RefundRequest.java
- src/main/java/uk/gov/companieshouse/model/dto/payment/RefundResponse.java
- src/main/java/uk/gov/companieshouse/model/enums/RefundStatus.java
- src/main/java/uk/gov/companieshouse/service/dissolution/DissolutionRefundService.java
- src/main/java/uk/gov/companieshouse/service/dissolution/chips/ChipsResponseService.java
- src/main/java/uk/gov/companieshouse/service/payment/RefundService.java
- src/main/resources/application.yml
- src/test/java/uk/gov/companieshouse/client/PaymentsClientTest.java
- src/test/java/uk/gov/companieshouse/fixtures/DissolutionFixtures.java
- src/test/java/uk/gov/companieshouse/fixtures/PaymentFixtures.java
- src/test/java/uk/gov/companieshouse/service/dissolution/DissolutionRefundServiceTest.java
- src/test/java/uk/gov/companieshouse/service/dissolution/chips/ChipsResponseServiceTest.java
- src/test/java/uk/gov/companieshouse/service/payment/RefundServiceTest.java
- src/test/resources/application.yml
Added logic for creating a refund application upon dissolution application rejection
https://companieshouse.atlassian.net/browse/S4-252
> S4-252: Added logic to initiate a refund on rejected CHIPS response

- pom.xml
> Bumped parent pom version

- src/main/java/uk/gov/companieshouse/mapper/DirectorApprovalMapper.java
- src/main/java/uk/gov/companieshouse/mapper/DissolutionRequestMapper.java
- src/main/java/uk/gov/companieshouse/mapper/email/EmailMapper.java
- src/main/java/uk/gov/companieshouse/service/barcode/BarcodeGenerator.java
- src/main/java/uk/gov/companieshouse/service/dissolution/DissolutionEmailService.java
- src/main/java/uk/gov/companieshouse/service/dissolution/chips/ChipsSubmitter.java
- src/main/java/uk/gov/companieshouse/service/dissolution/chips/DissolutionChipsService.java
See JSON in JIRA ticket.
https://companieshouse.atlassian.net/browse/S4-278
> hotfix/S4-278 - UTC Date Times

- src/main/java/uk/gov/companieshouse/service/dissolution/DissolutionPatcher.java
- src/main/java/uk/gov/companieshouse/service/dissolution/DissolutionService.java
- src/test/java/uk/gov/companieshouse/service/dissolution/DissolutionPatcherTest.java
- src/test/java/uk/gov/companieshouse/service/dissolution/DissolutionServiceTest.java
> hotfix/S4-254 - Patch Payment by reference

- src/main/java/uk/gov/companieshouse/controller/PaymentController.java
- src/test/java/uk/gov/companieshouse/controller/PaymentControllerTest.java
Update payment endpoint to return 204
https://companieshouse.atlassian.net/browse/S4-304
> Update payment endpoint to return 204

- src/main/java/uk/gov/companieshouse/service/dissolution/DissolutionEmailService.java
- src/test/java/uk/gov/companieshouse/service/dissolution/DissolutionEmailServiceTest.java
Stop sending emails to signatories who are also applicants
https://companieshouse.atlassian.net/browse/S4-264
> Stop sending emails to signatories who are also applicants

- src/main/resources/pdf_templates/ds01.html
- src/main/resources/pdf_templates/llds01.html
Updated HTML PDF template
https://companieshouse.atlassian.net/browse/BI-5925
> BI-5925: Removed company name from PDF template title

- src/main/java/uk/gov/companieshouse/config/FeatureToggleConfig.java
- src/main/java/uk/gov/companieshouse/controller/PaymentController.java
- src/main/java/uk/gov/companieshouse/mapper/PaymentInformationMapper.java
- src/main/java/uk/gov/companieshouse/mapper/chips/ChipsFormDataMapper.java
- src/main/java/uk/gov/companieshouse/model/db/payment/PaymentInformation.java
- src/main/java/uk/gov/companieshouse/model/dto/chips/xml/ChipsPayment.java
- src/main/java/uk/gov/companieshouse/model/dto/chips/xml/ChipsPaymentMethod.java
- src/main/java/uk/gov/companieshouse/model/dto/payment/PaymentPatchRequest.java
- src/main/java/uk/gov/companieshouse/model/enums/PaymentMethod.java
- src/main/java/uk/gov/companieshouse/service/dissolution/DissolutionPatcher.java
- src/main/java/uk/gov/companieshouse/service/dissolution/DissolutionService.java
- src/main/java/uk/gov/companieshouse/service/dissolution/chips/ChipsResponseService.java
- src/main/java/uk/gov/companieshouse/service/dissolution/validator/PaymentValidator.java
- src/main/resources/application.yml
- src/test/java/uk/gov/companieshouse/controller/PaymentControllerTest.java
- src/test/java/uk/gov/companieshouse/mapper/PaymentInformationMapperTest.java
- src/test/java/uk/gov/companieshouse/mapper/chips/ChipsFormDataMapperTest.java
- src/test/java/uk/gov/companieshouse/service/dissolution/DissolutionPatcherTest.java
- src/test/java/uk/gov/companieshouse/service/dissolution/DissolutionServiceTest.java
- src/test/java/uk/gov/companieshouse/service/dissolution/chips/ChipsResponseServiceTest.java
- src/test/java/uk/gov/companieshouse/service/dissolution/validator/PaymentValidatorTest.java
- Update PATCH payment endpoint to accept and save account number for "Pay by account" payments.
- Add validator to validate payment patch request.
- "Pay by account" functionality is feature toggled.
Depends on https://github.com/companieshouse/dissolution-web/pull/234.
https://companieshouse.atlassian.net/browse/BI-5811
> feature/BI-5811: Update PATCH payment endpoint to accept and save account number for "Pay by account" payments.

- Makefile
- pom.xml
- suppressed-security-checks.xml
Added task to run OWASP scan for security checks
https://companieshouse.atlassian.net/browse/BI-5980
> BI-5980: Implement standardised security checks to dissolutions

- pom.xml
> Expand classpath in Docker to avoid issues with wildcard classpaths

- src/main/java/uk/gov/companieshouse/config/FeatureToggleConfig.java
- src/main/java/uk/gov/companieshouse/service/dissolution/chips/ChipsResponseService.java
- src/main/resources/application.yml
- src/test/java/uk/gov/companieshouse/service/dissolution/chips/ChipsResponseServiceTest.java
https://github.com/companieshouse/dissolution-api/pull/150
https://github.com/companieshouse/chs-configs/pull/1384
https://github.com/companieshouse/docker-chs-development/pull/98
https://companieshouse.atlassian.net/browse/BI-6239
> feature/BI-6239 - Remove refunds feature toggle

- pom.xml
- src/main/java/uk/gov/companieshouse/mapper/email/DissolutionEmailMapper.java
- src/main/java/uk/gov/companieshouse/service/dissolution/DissolutionEmailService.java
- src/test/java/uk/gov/companieshouse/fixtures/EmailFixtures.java
- src/test/java/uk/gov/companieshouse/mapper/email/DissolutionEmailMapperTest.java
- src/test/java/uk/gov/companieshouse/service/dissolution/DissolutionEmailServiceTest.java
Send application accepted email to all directors involved in voluntary dissolution of company. Previously email was only sent out to the creator of the application.
BI-6441
https://companieshouse.atlassian.net/browse/BI-6441
> Send application accepted email to all directors involved in voluntary dissolution of company

- src/main/java/uk/gov/companieshouse/mapper/email/DissolutionEmailMapper.java
Alert email sent out to support team when service fails
https://companieshouse.atlassian.net/browse/BI-5890
> Alert email sent to support team when service fails

- pom.xml
> update spring boot and remove specific mongodb version dependency

- pom.xml
> update dependencies netty and flapdoodle

- pom.xml
> update spring boot version

- pom.xml
Security fix to log4j version
DEBT-1408
> Bump structured logging version and add log4j 2.16

- pom.xml
Reverts companieshouse/dissolution-api#620
> Revert "Bump software.amazon.awssdk:bom from 2.15.20 to 2.17.247"

- src/main/java/uk/gov/companieshouse/model/dto/payment/PaymentPatchRequest.java
Due to changes to the refund patch request here: https://github.com/companieshouse/payment-processed-consumer/commit/eabfbe87e879b24db09f926506b332190923523e#diff-dbdc7d5ec8a4a5729f2f656906a0efac65520449b9655486229699fb04f904efR9 the model for that patch request needed updating to include the new fields.
The change to the model in the consumer was throwing errors in the dissolution-api due to unrecognised fields.
https://companieshouse.atlassian.net/browse/ROE-1914
- [ x] Acceptance Criteria met
- [x ] Branch named {feature|hotfix|task}/{S4-*}
- [ x] Commit messages are meaningful
- [ x] Manually tested
- [ x] Pulled latest master into feature branch
> Add fields required for handling the refund patch request

- src/main/java/uk/gov/companieshouse/model/enums/RefundStatus.java
Update refund status to mirror Payments API response
https://github.com/companieshouse/payments.api.ch.gov.uk/blob/master/mappers/refund.go#L40-L44
ROE-1984
> Refund Statuses

- src/main/java/uk/gov/companieshouse/client/PaymentsClient.java
- src/main/java/uk/gov/companieshouse/controller/DissolutionController.java
- src/main/java/uk/gov/companieshouse/service/payment/PaymentService.java
If error occurs when getting payment status, remove payment reference from Dissolution in mongoDB to allow user to restart payment.
BI-13498
> Restart payment if error getting status

- src/main/java/uk/gov/companieshouse/model/Constants.java
- Updated the fee value from £8 to £33
- Work for this ticket (FEE-76) was done on FEE-78's feature branch
[FEE-76](https://companieshouse.atlassian.net/browse/FEE-76)
[FEE-78](https://companieshouse.atlassian.net/browse/FEE-78)
- Demo videos have been recorded for both tickets, showing the user journey and the fee changes meeting the accepted criteria. 
- Screenshots of the acceptance criteria being met are available to see on the Jira Tickets.
[FEE-76]: https://companieshouse.atlassian.net/browse/FEE-76?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FEE-78]: https://companieshouse.atlassian.net/browse/FEE-78?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …
> fee-78-s-update-ds01-fee-chs

- src/main/java/uk/gov/companieshouse/model/Constants.java
Updated the fee value from £8 to £33
[FEE-76]
[FEE-78]
[FEE-76]: https://companieshouse.atlassian.net/browse/FEE-76?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FEE-78]: https://companieshouse.atlassian.net/browse/FEE-78?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fee 78 s update ds01 fee chs

- src/main/java/uk/gov/companieshouse/service/dissolution/DissolutionRefundService.java
- src/test/java/uk/gov/companieshouse/fixtures/PaymentFixtures.java
- src/test/java/uk/gov/companieshouse/mapper/RefundRequestMapperTest.java
- src/test/java/uk/gov/companieshouse/service/dissolution/DissolutionRefundServiceTest.java
Update refund amount to £33; Also updated payment amounts in test fixtures for consistency
[FEE-225]
[FEE-225]: https://companieshouse.atlassian.net/browse/FEE-225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update refund amount to £33 (FEE-225)

- pom.xml
- src/main/java/uk/gov/companieshouse/controller/DissolutionController.java
- src/main/java/uk/gov/companieshouse/exception/CompanyProfileServiceException.java
- src/main/java/uk/gov/companieshouse/exception/ServiceUnavailableException.java
- src/main/java/uk/gov/companieshouse/service/CompanyProfileServiceA.java
- src/main/java/uk/gov/companieshouse/service/CompanyServiceProfileAImpl.java
- src/test/java/uk/gov/companieshouse/service/dissolution/DissolutionPatcherTest.java
TODO: code cleanup and renaming of wip classes
> changes for company-profile

- terraform/groups/ecs-service/iam.tf
- terraform/groups/ecs-service/locals.tf
- terraform/groups/ecs-service/main.tf
Added resources to define an IAM policy that permits access from the ECS task to the dissolutions S3 bucket.
> Add IAM policy to permit access to dissolutions bucket

- terraform/groups/ecs-service/iam.tf
Updated IAM policy to allow the service to write objects in S3
> Update IAM policy

- README.md
> Adding ecs to readme

- src/main/resources/application.yml
> Add back missing logging namespace property

- CODEOWNERS
- Makefile
- pom.xml
Updated pipeline & Makefile for sonarQube
Addressed security vulnerabilities
[ASM-402](https://companieshouse.atlassian.net/browse/ASM-402)
[ASM-402]: https://companieshouse.atlassian.net/browse/ASM-402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ASM-402 periodic maintenance

- pom.xml
Picked up latest version of private-api-sdk-java
Addressed 2 other dependency check issues
[ASM-402](https://companieshouse.atlassian.net/browse/ASM-402)
[ASM-402]: https://companieshouse.atlassian.net/browse/ASM-402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ASM-402 bump private-api-sdk-java and other security vulnerabilities

- src/main/java/uk/gov/companieshouse/config/LoggingConfig.java
- src/main/java/uk/gov/companieshouse/config/SecurityConfig.java
- src/main/resources/application.yml
- terraform/groups/ecs-service/locals.tf
updating healthcheck path
https://companieshouse.atlassian.net/browse/JU-1769
> updating healthcheck path
