.github/pull_request_template.md, src/main/java/uk/gov/companieshouse/config/SecurityConfig.java, src/test/java/uk/gov/companieshouse/controller/DissolutionControllerTest.java, src/test/java/uk/gov/companieshouse/controller/PaymentControllerTest.java, src/test/java/uk/gov/companieshouse/controller/SubmitControllerTest.java
- Add API authentication on endpoints used by external APIs/services.
- Add pull request template.
Relates to https://github.com/companieshouse/taf-api-karate/pull/190.
=> feature/S4-75: Add API authentication on endpoints used by external APIs/services.

src/main/java/uk/gov/companieshouse/mapper/chips/DissolutionChipsMapper.java, src/main/java/uk/gov/companieshouse/service/dissolution/certificate/DissolutionCertificateDownloader.java, src/main/java/uk/gov/companieshouse/service/dissolution/chips/ChipsSubmitter.java, src/test/java/uk/gov/companieshouse/mapper/chips/DissolutionChipsMapperTest.java, src/test/java/uk/gov/companieshouse/service/dissolution/certificate/DissolutionCertificateDownloaderTest.java, src/test/java/uk/gov/companieshouse/service/dissolution/chips/ChipsSubmitterTest.java
Coverting to UTF8 was changing to contents of the PDF, causing it to render blank in chips. Now going from byte[] -> base 64 string
=> hotfix/S4-101 - Dissolution Certificate CHIPS Submission

src/main/java/uk/gov/companieshouse/model/enums/OfficerRole.java, src/main/java/uk/gov/companieshouse/service/CompanyOfficerValidator.java, src/test/java/uk/gov/companieshouse/service/CompanyOfficerValidatorTest.java
LLP members are not displaying on the select director screen. This makes testing of LLPs with accurate data impossible.
Depends on: 
https://github.com/companieshouse/dissolution-web/pull/79
- [] Code reviewed
=> Add Officer Role - LLP Member

src/main/java/uk/gov/companieshouse/mapper/email/DissolutionEmailMapper.java, src/main/java/uk/gov/companieshouse/mapper/email/EmailMapper.java, src/main/java/uk/gov/companieshouse/model/Constants.java, src/main/java/uk/gov/companieshouse/model/dto/email/SignatoryToSignEmailData.java, src/main/java/uk/gov/companieshouse/service/dissolution/DissolutionCreator.java, src/main/java/uk/gov/companieshouse/service/dissolution/DissolutionDeadlineDateCalculator.java, src/main/java/uk/gov/companieshouse/service/dissolution/DissolutionEmailService.java, src/main/java/uk/gov/companieshouse/service/email/EmailService.java, src/test/java/uk/gov/companieshouse/fixtures/EmailFixtures.java, src/test/java/uk/gov/companieshouse/mapper/email/DissolutionEmailMapperTest.java, src/test/java/uk/gov/companieshouse/mapper/email/EmailMapperTest.java, src/test/java/uk/gov/companieshouse/service/dissolution/DissolutionCreatorTest.java, src/test/java/uk/gov/companieshouse/service/dissolution/DissolutionDeadlineDateCalculatorTest.java, src/test/java/uk/gov/companieshouse/service/email/DissolutionEmailServiceTest.java, src/test/java/uk/gov/companieshouse/service/email/EmailServiceTest.java
dissolution-api - https://github.com/companieshouse/dissolution-api/pull/45
chs-notification-api - https://github.com/companieshouse/chs-notification-api/pull/192
* Sending an email called `dissolution-signatory-to-sign` to each unique signatory email address
* Removed class level generic from EmailMapper to prevent coupling to a single model per dependent. The generic is now method level rather than class level
=> feature/S4-95 - Email Signatories to Sign

src/main/java/uk/gov/companieshouse/controller/PaymentController.java, src/main/java/uk/gov/companieshouse/model/Constants.java, src/main/java/uk/gov/companieshouse/model/dto/payment/PaymentItem.java, src/main/java/uk/gov/companieshouse/service/payment/PaymentService.java, src/test/java/uk/gov/companieshouse/controller/PaymentControllerTest.java, src/test/java/uk/gov/companieshouse/fixtures/PaymentFixtures.java, src/test/java/uk/gov/companieshouse/service/dissolution/PaymentServiceTest.java
Update tests
Product type is now dependant on whether the application is DS01 or LLDS01
- [ n/a] 3 Amigos
- [ x] Acceptance Criteria met
- [ x] Branch named {feature|hotfix|task}/{S4-*}
- [ x] Commit messages are meaningful
- [ x] Manually tested
- [ x] All unit tests passing
- [ x] API (Karate) tests passing
- [ x] Pulled latest master into feature branch
- [ x] Code reviewed
- [ n/a] New Docker environment variables have also been added to the revel1 environment and cidev environment
- [ n/a] If your pull request depends on any other, please link them in the description
=> Add product type depending on the type of application

src/main/java/uk/gov/companieshouse/mapper/DissolutionRequestMapper.java, src/main/java/uk/gov/companieshouse/model/db/dissolution/Dissolution.java, src/main/java/uk/gov/companieshouse/repository/DissolutionRepository.java, src/main/java/uk/gov/companieshouse/service/dissolution/chips/ChipsResponseService.java, src/test/java/uk/gov/companieshouse/fixtures/DissolutionFixtures.java, src/test/java/uk/gov/companieshouse/mapper/DissolutionRequestMapperTest.java, src/test/java/uk/gov/companieshouse/repository/dissolution/DissolutionRepositoryTest.java, src/test/java/uk/gov/companieshouse/service/dissolution/chips/ChipsResponseServiceTest.java
Mark dissolutions as active when saving to Mongo
Fetch only active Dissolution
Mark dissolution as inactive when verdict is received from CHIPS
- [n/a] New Docker environment variables have also been added to the rebel1 environment and cidev environment
- [n/a] If your pull request depends on any other, please link them in the description
=> Enable multiple dissolutions

src/main/java/uk/gov/companieshouse/config/EnvironmentConfig.java, src/main/java/uk/gov/companieshouse/mapper/email/DissolutionEmailMapper.java, src/main/java/uk/gov/companieshouse/model/dto/email/ApplicationAcceptedEmailData.java, src/main/java/uk/gov/companieshouse/model/dto/email/ApplicationRejectedEmailData.java, src/main/java/uk/gov/companieshouse/model/dto/email/SuccessfulPaymentEmailData.java, src/main/java/uk/gov/companieshouse/service/dissolution/DissolutionEmailService.java, src/main/resources/application.yml, src/test/java/uk/gov/companieshouse/mapper/email/DissolutionEmailMapperTest.java, src/test/java/uk/gov/companieshouse/service/dissolution/DissolutionEmailServiceTest.java
+ Added sending email to finance if application is rejected
Added payment reference to email data and logic for sending a copy of the rejection email to CH Finance
https://companieshouse.atlassian.net/browse/S4-238
=> S4-238: Added payment reference to email data structure

src/main/java/uk/gov/companieshouse/mapper/chips/ChipsFormDataMapper.java, src/test/java/uk/gov/companieshouse/mapper/chips/ChipsFormDataMapperTest.java
An officer with a name `DOE, John James` is sent to CHIPS as:
```
<personName>
<forename>John James</forename>
<surname>DOE</surname>
</personName>
```
But for some companies, another company can be listed as a director. Companies do not neccessarily have commas in their names, and caused the CHIPS submission code to break. Such names such be submitted as:
```
<personName>
<surname>I AM A COMPANY</surname>
</personName>
```
=> hotfix/S4-297 - Handle companies as directors

src/main/java/uk/gov/companieshouse/controller/DissolutionController.java, src/main/java/uk/gov/companieshouse/model/dto/dissolution/DissolutionPatchRequest.java, src/main/java/uk/gov/companieshouse/service/dissolution/DissolutionPatcher.java, src/main/java/uk/gov/companieshouse/service/dissolution/DissolutionService.java, src/test/java/uk/gov/companieshouse/controller/DissolutionControllerTest.java, src/test/java/uk/gov/companieshouse/fixtures/DissolutionFixtures.java, src/test/java/uk/gov/companieshouse/service/dissolution/DissolutionPatcherTest.java, src/test/java/uk/gov/companieshouse/service/dissolution/DissolutionServiceTest.java
- Added recieving IP from patch request
Added IP to the patch request model so that we can store the correct IP address
https://companieshouse.atlassian.net/browse/S4-279
=> S4-279: Fix for incorrect IP being stored by patch request

src/main/java/uk/gov/companieshouse/config/SecurityConfig.java, src/main/java/uk/gov/companieshouse/controller/PaymentController.java, src/main/java/uk/gov/companieshouse/mapper/DissolutionResponseMapper.java, src/main/java/uk/gov/companieshouse/service/dissolution/DissolutionGetter.java, src/main/java/uk/gov/companieshouse/service/dissolution/DissolutionPatcher.java, src/main/java/uk/gov/companieshouse/service/dissolution/DissolutionService.java, src/main/java/uk/gov/companieshouse/service/payment/PaymentService.java, src/test/java/uk/gov/companieshouse/controller/PaymentControllerTest.java, src/test/java/uk/gov/companieshouse/mapper/DissolutionResponseMapperTest.java, src/test/java/uk/gov/companieshouse/service/dissolution/DissolutionGetterTest.java, src/test/java/uk/gov/companieshouse/service/dissolution/DissolutionPatcherTest.java, src/test/java/uk/gov/companieshouse/service/dissolution/DissolutionServiceTest.java, src/test/java/uk/gov/companieshouse/service/dissolution/PaymentServiceTest.java
Due to refunds reconciliation being async, the dissolution may be marked as inactive before the refund is fully reconciled. This causes a 404 on the dissolution api because the company number does not have an active dissolution.
By using the reference, we no longer have to rely on the active flag as it is always unique.
=> Use application reference instead of company number in payment endpoints

src/main/java/uk/gov/companieshouse/controller/ResendEmailController.java, src/test/java/uk/gov/companieshouse/controller/ResendEmailControllerTest.java
Creation of new endpoint in dissolution api repo to be called from dissolution web to resend email out for signatories to sign.
Dependant on Dissolution-web changes from: https://github.com/companieshouse/dissolution-web/pull/335
BI-6211, BI-6212
=> New endpoint in dissolution-api for resend signatory email functionality 

pom.xml, src/main/java/uk/gov/companieshouse/service/dissolution/DissolutionPatcher.java, src/test/java/uk/gov/companieshouse/service/dissolution/DissolutionPatcherTest.java
Stop payment email being sent out when processing dissolution of single director companies.
Update spring boot to version 2.4.3,
Force correct version of Netty that were missed in other dependancies,
Resolving tomcat-embed and Netty vulnerabilities.
BI-6898, BI-6412
=> Stop payment email being sent out for single director companies

src/main/java/uk/gov/companieshouse/config/SecurityConfig.java
Needed to include the resend email path to authentication list so that it can be authenticated to respond to dissolution-web call.
[BI-6211](https://companieshouse.atlassian.net/browse/BI-6211)
=> Add resend email path to the authentication list

src/main/java/uk/gov/companieshouse/config/EnvironmentConfig.java, src/main/java/uk/gov/companieshouse/mapper/email/DissolutionEmailMapper.java, src/main/java/uk/gov/companieshouse/model/Constants.java, src/main/java/uk/gov/companieshouse/model/dto/email/MessageType.java, src/main/java/uk/gov/companieshouse/model/dto/email/SupportNotificationEmailData.java, src/main/java/uk/gov/companieshouse/service/dissolution/DissolutionEmailService.java, src/main/java/uk/gov/companieshouse/service/dissolution/chips/ChipsSubmitter.java, src/main/resources/application.yml, src/test/java/uk/gov/companieshouse/fixtures/EmailFixtures.java, src/test/java/uk/gov/companieshouse/mapper/email/DissolutionEmailMapperTest.java, src/test/java/uk/gov/companieshouse/service/dissolution/DissolutionEmailServiceTest.java, src/test/java/uk/gov/companieshouse/service/dissolution/chips/ChipsSubmitterTest.java
An email notification alert sent to Support when an attempt to submit an eDS01 to CHIPS has failed. The email is triggered when the maximum number of retries have been exhausted.
[BI-7217](https://companieshouse.atlassian.net/browse/BI-7217) -> [BI-5893](https://companieshouse.atlassian.net/browse/BI-5893)
=> CHIPS eDS01 submission failure alert

src/main/java/uk/gov/companieshouse/mapper/email/DissolutionEmailMapper.java
Add support email to rebel1 env to alert internal support team of application failure. 
Reverting temporary email used for testing purposes from commit: https://github.com/companieshouse/dissolution-api/commit/72f317208e2fa88cf3a2d081aee5202d61f99c83
BI-5893 https://companieshouse.atlassian.net/browse/BI-5893
=> Add support email for alert of application failure

src/main/java/uk/gov/companieshouse/service/dissolution/chips/ChipsSubmitter.java, src/test/java/uk/gov/companieshouse/service/dissolution/chips/ChipsSubmitterTest.java
Move function for emailing support to trigger only on chips submission failure previously triggered regardless of test failure for testing purposes. See comments on jira ticket for more information
BI-5893 https://companieshouse.atlassian.net/browse/BI-5893
=> Email to support to trigger on Chips submission failure

suppressed-security-checks.xml
Security check is failing on the netty-tcnative-classes dependency. This is a false positive as the regex used by the security software does not account for this dependency. For more info see open issue: https://github.com/jeremylong/DependencyCheck/issues/3865
DEBT-1408
=> Suppress netty-tcnative-classes false positive security issue

pom.xml
Reverts companieshouse/dissolution-api#607
=> Revert "Bump de.flapdoodle.embed.mongo from 3.0.0 to 3.4.8"

src/main/java/uk/gov/companieshouse/client/PaymentsClient.java, src/main/java/uk/gov/companieshouse/controller/DissolutionController.java, src/main/java/uk/gov/companieshouse/controller/PaymentController.java, src/main/java/uk/gov/companieshouse/mapper/DissolutionResponseMapper.java, src/main/java/uk/gov/companieshouse/mapper/PaymentInformationMapper.java, src/main/java/uk/gov/companieshouse/model/dto/dissolution/DissolutionGetResponse.java, src/main/java/uk/gov/companieshouse/model/dto/payment/PaymentDetailsResponse.java, src/main/java/uk/gov/companieshouse/service/dissolution/DissolutionPatcher.java, src/main/java/uk/gov/companieshouse/service/dissolution/DissolutionService.java, src/main/java/uk/gov/companieshouse/service/payment/PaymentService.java
For dissolution submissions with pending-payment status, make a call to Payments API to get correct up-to-date status, as payment could be complete.
Also add functionality to store Payment Reference in dissolution when creating payment, as this is needed to retrieve the payment later in the journey.
BI-12788
=> Payment status

pom.xml
New version of private-api-sdk-java was causing issues with tomcat starting
=> fix: build issue due to dependency version causing error

src/main/resources/application.yml
dissolution-api logging is very verbose. The thought is that this block is not usually needed in a CH service and removing it will make our logs more readable.
[CC-1818](https://companieshouse.atlassian.net/browse/CC-1818)
[CC-1818]: https://companieshouse.atlassian.net/browse/CC-1818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Reduce logging verbosity by removing global config
